// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
// See the LICENSE file in the project root for more information.

using System.Globalization;
using System.IO;
using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Roslyn.Test.Utilities.TestGenerators;
using Xunit;
using static Roslyn.Test.Utilities.SharedResourceHelpers;

namespace Metalama.Compiler.UnitTests;

public partial class SourceTransformersTests
{
    /// <summary>
    ///     Regression test for https://github.com/metalama/Metalama/issues/1405.
    ///     Verifies that a third-party source generator (simulated here as an IIncrementalGenerator
    ///     that reads AdditionalTexts) still produces output when a source transformer replaces all
    ///     syntax trees in the compilation.
    /// </summary>
    [Fact]
    public void ThirdPartyGeneratorWorksWithTransformer()
    {
        var dir = Temp.CreateDirectory();

        // Source file that references a member generated by the source generator.
        var src = dir.CreateFile("SR.cs").WriteAllText("""
            partial class SR
            {
                public static string GetValue() => ResourceManager;
            }
            """);

        // Additional file that the source generator reads to produce code.
        var additionalFile = dir.CreateFile("Resources.resx").WriteAllText("<root></root>");

        var args = new[]
        {
            "/t:library",
            $"/additionalfile:{additionalFile.Path}",
            src.Path
        };

        // Create a source generator that generates a partial class with the ResourceManager property.
        var generator = new PipelineCallbackGenerator(ctx =>
        {
            // Register a provider that reads additional files and generates code.
            var additionalTexts = ctx.AdditionalTextsProvider
                .Where(static t => t.Path.EndsWith(".resx"));

            ctx.RegisterSourceOutput(additionalTexts, static (spc, _) =>
            {
                spc.AddSource("SR.Generated.cs", """
                    partial class SR
                    {
                        public static string ResourceManager => "generated";
                    }
                    """);
            });
        });

        // Create a transformer that replaces all syntax trees (similar to what Metalama.SourceTransformer does).
        var transformer = new AllTreeReplacingTransformer();

        var csc = CreateCSharpCompiler(null, dir.Path, args,
            generators: [generator.AsSourceGenerator()],
            transformers: [transformer]);

        var outWriter = new StringWriter(CultureInfo.InvariantCulture);
        var exitCode = csc.Run(outWriter);
        var output = outWriter.ToString();

        // The build should succeed: the transformer replaces trees, and the generator should still run
        // and produce the ResourceManager property that SR.cs depends on.
        Assert.True(exitCode == 0, $"Build failed with exit code {exitCode}. Output:\n{output}");

        CleanupAllGeneratedFiles(src.Path);
    }

    /// <summary>
    ///     Regression test for https://github.com/metalama/Metalama/issues/1405.
    ///     More accurately simulates the Catglobe.ResXFileCodeGenerator pipeline which
    ///     uses both AdditionalTextsProvider and ForAttributeWithMetadataName combined
    ///     via Combine/Collect.
    /// </summary>
    [Fact]
    public void ThirdPartyGeneratorWithForAttributeCombinedWorksWithTransformer()
    {
        var dir = Temp.CreateDirectory();

        // Source file that references a member generated by the source generator.
        var src = dir.CreateFile("SR.cs").WriteAllText("""
            partial class SR
            {
                public static string GetValue() => ResourceManager;
            }
            """);

        // Additional file that the source generator reads to produce code.
        var additionalFile = dir.CreateFile("Resources.resx").WriteAllText("<root></root>");

        var args = new[]
        {
            "/t:library",
            $"/additionalfile:{additionalFile.Path}",
            src.Path
        };

        // Create a generator that mimics Catglobe's pipeline:
        // 1. AdditionalTextsProvider for .resx files
        // 2. ForAttributeWithMetadataName for an optional settings attribute
        // 3. Combine the two pipelines
        // 4. Only generate output for unmatched .resx files
        var generator = new PipelineCallbackGenerator(ctx =>
        {
            // Pipeline 1: Collect resx files from additional texts
            var resxFiles = ctx.AdditionalTextsProvider
                .Where(static t => t.Path.EndsWith(".resx"))
                .Collect();

            // Pipeline 2: ForAttributeWithMetadataName (will find nothing since no attribute exists)
            // This mimics the Catglobe generator's use of ForAttributeWithMetadataName
            // for ResxSettingsAttribute combined with Collect
            var classSpecs = ctx.SyntaxProvider
                .ForAttributeWithMetadataName<string?>(
                    "System.ObsoleteAttribute", // Using a known attribute as stand-in
                    predicate: static (node, _) => node is ClassDeclarationSyntax,
                    transform: static (context, _) => context.TargetSymbol.Name)
                .Collect();

            // Pipeline 3: Combine resx files with the (empty) class specs.
            // This is the critical pattern - combining AdditionalTexts with ForAttributeWithMetadataName results.
            var combined = resxFiles.Combine(classSpecs);

            ctx.RegisterSourceOutput(combined, static (spc, pair) =>
            {
                var (resxTexts, _) = pair;
                // Generate code for each resx file that doesn't match a class
                foreach (var resx in resxTexts)
                {
                    spc.AddSource("SR.Generated.cs", """
                        partial class SR
                        {
                            public static string ResourceManager => "generated";
                        }
                        """);
                }
            });
        });

        // Create a transformer that replaces all syntax trees.
        var transformer = new AllTreeReplacingTransformer();

        var csc = CreateCSharpCompiler(null, dir.Path, args,
            generators: [generator.AsSourceGenerator()],
            transformers: [transformer]);

        var outWriter = new StringWriter(CultureInfo.InvariantCulture);
        var exitCode = csc.Run(outWriter);
        var output = outWriter.ToString();

        // The build should succeed: the transformer replaces trees, and the generator should still run.
        Assert.True(exitCode == 0, $"Build failed with exit code {exitCode}. Output:\n{output}");

        CleanupAllGeneratedFiles(src.Path);
    }

    /// <summary>
    ///     Regression test for https://github.com/metalama/Metalama/issues/1405.
    ///     Verifies that AnalyzerConfigOptionsProvider.GetOptions(SyntaxTree) returns correct
    ///     options for transformed syntax trees when a generator queries per-tree options.
    ///     This is the core bug: the unmapped provider was passed to RunGenerators, so
    ///     GetOptions returned empty for all transformed trees.
    /// </summary>
    [Fact]
    public void GeneratorReceivesMappedAnalyzerConfigOptionsAfterTransformer()
    {
        var dir = Temp.CreateDirectory();

        // Source file whose tree-specific options will be queried by the generator.
        var src = dir.CreateFile("SR.cs").WriteAllText("""
            partial class SR
            {
                public static string GetValue() => GeneratedProperty;
            }
            """);

        // Create a globalconfig with a per-file section using the absolute path of the source file.
        // This maps the source file to specific analyzer config options.
        var editorConfig = dir.CreateFile(".globalconfig").WriteAllText($"""
            is_global = true

            [{src.Path.Replace("\\", "/")}]
            build_metadata.Compile.MyCustomOption = CustomValue
            """);

        var args = new[]
        {
            "/t:library",
            $"/analyzerconfig:{editorConfig.Path}",
            src.Path
        };

        // Create a generator that reads AnalyzerConfigOptions for each syntax tree.
        // If the options provider is unmapped (bug), GetOptions returns empty and the generator
        // won't find the custom option, so it won't generate the property.
        var generator = new PipelineCallbackGenerator(ctx =>
        {
            var syntaxTrees = ctx.SyntaxProvider.CreateSyntaxProvider(
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (context, _) => context.Node.SyntaxTree);

            var combined = syntaxTrees.Combine(ctx.AnalyzerConfigOptionsProvider);

            ctx.RegisterSourceOutput(combined, static (spc, pair) =>
            {
                var (tree, provider) = pair;
                var options = provider.GetOptions(tree);

                // The generator only produces output if the per-tree option is found.
                if (options.TryGetValue("build_metadata.Compile.MyCustomOption", out var value)
                    && value == "CustomValue")
                {
                    spc.AddSource("SR.Generated.cs", """
                        partial class SR
                        {
                            public static string GeneratedProperty => "generated";
                        }
                        """);
                }
            });
        });

        // Create a transformer that replaces all syntax trees.
        var transformer = new AllTreeReplacingTransformer();

        var csc = CreateCSharpCompiler(null, dir.Path, args,
            generators: [generator.AsSourceGenerator()],
            transformers: [transformer]);

        var outWriter = new StringWriter(CultureInfo.InvariantCulture);
        var exitCode = csc.Run(outWriter);
        var output = outWriter.ToString();

        // Without the fix, the generator wouldn't find the per-tree options because
        // the unmapped provider was passed to RunGenerators. With the fix, the mapped
        // provider correctly resolves options for the transformed trees.
        Assert.True(exitCode == 0, $"Build failed with exit code {exitCode}. Output:\n{output}");

        CleanupAllGeneratedFiles(src.Path);
    }

    /// <summary>
    ///     Regression test for https://github.com/metalama/Metalama/issues/1405.
    ///     Simulates the exact Catglobe pattern: generator reads per-file AnalyzerConfigOptions
    ///     for AdditionalText files via Combine with AnalyzerConfigOptionsProvider.
    ///     This test verifies that GetOptions(AdditionalText) works correctly after transformers.
    /// </summary>
    [Fact]
    public void GeneratorReceivesAdditionalTextOptionsAfterTransformer()
    {
        var dir = Temp.CreateDirectory();

        // Source file that references a member generated by the source generator.
        var src = dir.CreateFile("SR.cs").WriteAllText("""
            partial class SR
            {
                public static string GetValue() => ResourceManager;
            }
            """);

        // Additional file simulating a .resx file.
        var additionalFile = dir.CreateFile("Resources.resx").WriteAllText("<root></root>");

        // Create a globalconfig that sets per-file options for the additional file.
        // This mimics the MSBuild-generated build_metadata.AdditionalFiles options.
        var editorConfig = dir.CreateFile(".globalconfig").WriteAllText($"""
            is_global = true

            [{additionalFile.Path.Replace("\\", "/")}]
            build_metadata.AdditionalFiles.CustomToolNamespace = System
            """);

        var args = new[]
        {
            "/t:library",
            $"/additionalfile:{additionalFile.Path}",
            $"/analyzerconfig:{editorConfig.Path}",
            src.Path
        };

        // Create a generator that mimics Catglobe's pattern:
        // 1. Read additional texts filtered to .resx
        // 2. Combine with AnalyzerConfigOptionsProvider
        // 3. Read per-file options via GetOptions(AdditionalText)
        // 4. Generate code only if the expected option is found
        var generator = new PipelineCallbackGenerator(ctx =>
        {
            var resxFiles = ctx.AdditionalTextsProvider
                .Where(static t => t.Path.EndsWith(".resx"));

            var combined = resxFiles.Combine(ctx.AnalyzerConfigOptionsProvider);

            ctx.RegisterSourceOutput(combined, static (spc, pair) =>
            {
                var (additionalText, provider) = pair;
                var options = provider.GetOptions(additionalText);

                // The generator only produces output if the per-file option is found.
                if (options.TryGetValue("build_metadata.AdditionalFiles.CustomToolNamespace", out var ns)
                    && ns == "System")
                {
                    spc.AddSource("SR.Generated.cs", """
                        partial class SR
                        {
                            public static string ResourceManager => "generated";
                        }
                        """);
                }
            });
        });

        // Create a transformer that replaces all syntax trees.
        var transformer = new AllTreeReplacingTransformer();

        var csc = CreateCSharpCompiler(null, dir.Path, args,
            generators: [generator.AsSourceGenerator()],
            transformers: [transformer]);

        var outWriter = new StringWriter(CultureInfo.InvariantCulture);
        var exitCode = csc.Run(outWriter);
        var output = outWriter.ToString();

        Assert.True(exitCode == 0, $"Build failed with exit code {exitCode}. Output:\n{output}");

        CleanupAllGeneratedFiles(src.Path);
    }

    /// <summary>
    ///     A transformer that replaces all syntax trees without making any semantic changes,
    ///     similar to what the Metalama.SourceTransformer does for [Memo] attributes.
    /// </summary>
    private class AllTreeReplacingTransformer : ISourceTransformer
    {
        public void Execute(TransformerContext context)
        {
            foreach (var tree in context.Compilation.SyntaxTrees)
            {
                var newRoot = tree.GetRoot();
                context.ReplaceSyntaxTree(tree, tree.WithRootAndOptions(newRoot, tree.Options));
            }
        }
    }

}
