// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
// See the LICENSE file in the project root for more information.

using System.Globalization;
using System.IO;
using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Roslyn.Test.Utilities.TestGenerators;
using Xunit;
using static Roslyn.Test.Utilities.SharedResourceHelpers;

namespace Metalama.Compiler.UnitTests;

public partial class SourceTransformersTests
{
    /// <summary>
    ///     Regression test for https://github.com/metalama/Metalama/issues/1405.
    ///     Verifies that a third-party source generator (simulated here as an IIncrementalGenerator
    ///     that reads AdditionalTexts) still produces output when a source transformer replaces all
    ///     syntax trees in the compilation.
    /// </summary>
    [Fact]
    public void ThirdPartyGeneratorWorksWithTransformer()
    {
        var dir = Temp.CreateDirectory();

        // Source file that references a member generated by the source generator.
        var src = dir.CreateFile("SR.cs").WriteAllText("""
            partial class SR
            {
                public static string GetValue() => ResourceManager;
            }
            """);

        // Additional file that the source generator reads to produce code.
        var additionalFile = dir.CreateFile("Resources.resx").WriteAllText("<root></root>");

        var args = new[]
        {
            "/t:library",
            $"/additionalfile:{additionalFile.Path}",
            src.Path
        };

        // Create a source generator that generates a partial class with the ResourceManager property.
        var generator = new PipelineCallbackGenerator(ctx =>
        {
            // Register a provider that reads additional files and generates code.
            var additionalTexts = ctx.AdditionalTextsProvider
                .Where(static t => t.Path.EndsWith(".resx"));

            ctx.RegisterSourceOutput(additionalTexts, static (spc, text) =>
            {
                spc.AddSource("SR.Generated.cs", """
                    partial class SR
                    {
                        public static string ResourceManager => "generated";
                    }
                    """);
            });
        });

        // Create a transformer that replaces all syntax trees (similar to what Metalama.SourceTransformer does).
        var transformer = new AllTreeReplacingTransformer();

        var csc = CreateCSharpCompiler(null, dir.Path, args,
            generators: [generator.AsSourceGenerator()],
            transformers: [transformer]);

        var outWriter = new StringWriter(CultureInfo.InvariantCulture);
        var exitCode = csc.Run(outWriter);
        var output = outWriter.ToString();

        // The build should succeed: the transformer replaces trees, and the generator should still run
        // and produce the ResourceManager property that SR.cs depends on.
        Assert.True(exitCode == 0, $"Build failed with exit code {exitCode}. Output:\n{output}");

        CleanupAllGeneratedFiles(src.Path);
    }

    /// <summary>
    ///     A transformer that replaces all syntax trees without making any semantic changes,
    ///     similar to what the Metalama.SourceTransformer does for [Memo] attributes.
    /// </summary>
    private class AllTreeReplacingTransformer : ISourceTransformer
    {
        public void Execute(TransformerContext context)
        {
            foreach (var tree in context.Compilation.SyntaxTrees)
            {
                var newRoot = tree.GetRoot();
                context.ReplaceSyntaxTree(tree, tree.WithRootAndOptions(newRoot, tree.Options));
            }
        }
    }
}
